(function(G){G['i18n_']={lc:{"cs":function(n){
  if (n == 1) {
    return 'one';
  }
  if (n == 2 || n == 3 || n == 4) {
    return 'few';
  }
  return 'other';
}},
c:function(d,k){if(!d)throw new Error("MessageFormat: Data required for '"+k+"'.")},
n:function(d,k,o){if(isNaN(d[k]))throw new Error("MessageFormat: '"+k+"' isn't a number.");return d[k]-(o||0)},
v:function(d,k){i18n_.c(d,k);return d[k]},
p:function(d,k,o,l,p){i18n_.c(d,k);return d[k] in p?p[d[k]]:(k=i18n_.lc[l](d[k]-o),k in p?p[k]:p.other)},
s:function(d,k,p){i18n_.c(d,k);return d[k] in p?p[d[k]]:p.other}}
i18n_["loginForm"]={
"welcome":function(d){return "<strong>Přihlaste se</strong> tam, kam se dosud nikdo nevydal."},
"done.enter":function(d){return "Vstoupit na"},
"done.login":function(d){return "Přihlásit se"},
"done.thanks":function(d){return "<strong>Blahopřejeme,</strong> registrace proběhla úspěšně :)"},
"login.submit":function(d){return "Přihlásit se"},
"login.remember":function(d){return "Pamatovat si mě na tomto počítači"},
"login.rememberUrl":function(d){return "http://napoveda.seznam.cz/cz/login/prihlaseni/"},
"login.new":function(d){return "Nejste zaregistrováni na Seznam.cz?"},
"login.register":function(d){return "Registrujte se!"},
"login.forgotten":function(d){return "Zaslat zapomenuté heslo"},
"login.forgottenUrl":function(d){return "http://napoveda.seznam.cz/cz/zapomenute-heslo.html"},
"login.cookies1":function(d){return "Pro správné přihlášení je potřeba zapnout cookies."},
"login.cookies2":function(d){return "Nevíte si rady? Podívejte se do"},
"login.cookies3":function(d){return "nápovědy"},
"login.email":function(d){return "Libovolný e-mail"},
"login.password":function(d){return "Heslo"},
"login.changePassword":function(d){return "Změnit heslo"},
"login.continueWeak":function(d){return "Pokračovat se současným heslem"},
"login.error.weak":function(d){return "Vaše heslo je příliš jednoduché!"},
"login.error.bad":function(d){return "Neexistující uživatel nebo chybné heslo!"},
"login.error.blocked":function(d){return "Váš účet je zablokován."},
"login.error.internal":function(d){return "Interní chyba systému."},
"login.licence.title":function(d){return "<strong>Zjednodušili jsme Smluvní podmínky</strong>"},
"login.licence.explain":function(d){return "Aby pro vás byly Smluvní podmínky srozumitelnější, rozhodli jsme se je k 1. 2. 2015 zpřehlednit. Přestože se pro vás nic nemění, prosíme o jejich opětovné odsouhlasení nejpozději do 31. 1. 2015."},
"login.licence.summary":function(d){return "Pro připomenutí tady jsou nejdůležitější body:"},
"login.licence.item1":function(d){return "S vaším e-mailovým účtem se můžete přihlásit i do našich ostatních služeb (Firmy.cz, Sklik.cz, Seznam peněženka, Mapy.cz, Lidé.cz aj.)"},
"login.licence.item2":function(d){return "Některé naše služby před prvním přihlášením vyžadují souhlas se zpracováním osobních údajů"},
"login.licence.full":function(d){return "V plném znění si podmínky můžete přelouskat v naší"},
"login.licence.help":function(d){return "Nápovědě"},
"login.licence.agree":function(d){return "Souhlasím s novými podmínkami"},
"login.licence.continue":function(d){return "Pokračovat"},
"register.title":function(d){return "<strong>Registrujte se</strong> a získáte obsah všech služeb Seznam.cz přímo na míru vašim potřebám."},
"register.continue":function(d){return "Pokračovat"},
"register.agree":function(d){return "Registrací souhlasíte s"},
"register.licence":function(d){return "podmínkami služby"},
"register.licenceUrl":function(d){return "http://napoveda.seznam.cz/cz/licencni-ujednani.html"},
"register.email":function(d){return "Libovolný e-mail"},
"register.password":function(d){return "Heslo"},
"register.password2":function(d){return "Zopakujte heslo"},
"register.new":function(d){return "Nemám e-mail a chci ho vytvořit"},
"register.login":function(d){return "Jsem registrovaný a chci se přihlásit"},
"register.resend":function(d){return "Zaslat znovu ověřovací kód"},
"register.resend2":function(d){return "Nepřišel vám kód?"},
"register.checkMail":function(d){return "Zkontrolujte svou e-mailovou schránku, kam jsme vám zaslali nový ověřovací kód."},
"register.finalize":function(d){return "Pro dokončení klikněte na odkaz, který jsme vám poslali na e-mail nebo opište zaslaný kód."},
"register.submit":function(d){return "Dokončit"},
"register.error.agree":function(d){return "Pro pokračování odsouhlaste podmínky služby"},
"register.error.403":function(d){return "Zadaný kód je neplatný"},
"register.error.404":function(d){return "Tento e-mail je u nás již registrován"},
"register.error.406":function(d){return "K registraci chybí heslo"},
"register.error.407":function(d){return "Pokus o registraci byl dočasně zablokován"},
"register.error.420":function(d){return "Vaše heslo je příliš slabé"},
"register.error.421":function(d){return "Vaše heslo je příliš slabé"},
"register.error.422":function(d){return "Vaše heslo je příliš krátké. Zadejte delší"},
"register.error.423":function(d){return "Vaše heslo je příliš dlouhé. Zadejte kratší"},
"register.error.424":function(d){return "Heslo obsahuje nepovolené znaky"},
"register.error.425":function(d){return "Na začátku či na konci hesla nesmí být mezera"},
"register.error.426":function(d){return "Hesla se neshodují"},
"register.error.427":function(d){return "Tato schránka ještě neexistuje. Kliknutím na 'Pokračovat' ji zaregistrujete."},
"register.error.430":function(d){return "Příliš krátký e-mail"},
"register.error.431":function(d){return "Zadaný e-mail je neplatný"},
"register.error.500":function(d){return "Interní chyba systému"}}
})(this);

