(function(G){G['i18n_']={lc:{"en":function(n){return n===1?"one":"other"}},
c:function(d,k){if(!d)throw new Error("MessageFormat: Data required for '"+k+"'.")},
n:function(d,k,o){if(isNaN(d[k]))throw new Error("MessageFormat: '"+k+"' isn't a number.");return d[k]-(o||0)},
v:function(d,k){i18n_.c(d,k);return d[k]},
p:function(d,k,o,l,p){i18n_.c(d,k);return d[k] in p?p[d[k]]:(k=i18n_.lc[l](d[k]-o),k in p?p[k]:p.other)},
s:function(d,k,p){i18n_.c(d,k);return d[k] in p?p[d[k]]:p.other}}
i18n_["loginForm"]={
"welcome":function(d){return "<strong>Sign in</strong> there, where no-one has set out up to now."},
"done.enter":function(d){return "Enter"},
"done.login":function(d){return "Sign in"},
"done.thanks":function(d){return "<strong>Congratulations, < /strong> your registration was successful :) "},
"login.submit":function(d){return "Sign in"},
"login.remember":function(d){return "Keep me signed in"},
"login.rememberUrl":function(d){return ""},
"login.new":function(d){return "Not registered on Seznam.cz?"},
"login.register":function(d){return "Sign up now!"},
"login.forgotten":function(d){return "Forgotten password?"},
"login.forgottenUrl":function(d){return "http://napoveda.seznam.cz/en/zapomenute-heslo.html"},
"login.cookies1":function(d){return "Cookies must be turned on in order to sign in correctly."},
"login.cookies2":function(d){return "Are you unaware of the recommendations? Take a look at the "},
"login.cookies3":function(d){return "help"},
"login.email":function(d){return "Any email address"},
"login.password":function(d){return "Password"},
"login.changePassword":function(d){return "Change password"},
"login.continueWeak":function(d){return "Continue with current password"},
"login.error.weak":function(d){return "Your password is too simple!"},
"login.error.bad":function(d){return "User does not exist or password incorrect!"},
"login.error.blocked":function(d){return "Your account has been blocked."},
"login.error.internal":function(d){return "Internal system error."},
"login.licence.title":function(d){return "<strong>We have simplified our Terms and Conditions</strong>"},
"login.licence.explain":function(d){return "In order to make the Terms and Conditions clearer for you, we have decided to clarify them as of 1 Feb. 2015. Even though it does not affect you in any way, we request that you accept them by 31 Jan. 2015."},
"login.licence.summary":function(d){return "As a reminder, here are the most important points: "},
"login.licence.item1":function(d){return "You can also sign in to our other services with your email account (Firmy.cz, Sklik.cz, Seznam pocket book, Mapy.cz, Lidé.cz etc. ) "},
"login.licence.item2":function(d){return "Some of our services require your consent to the processing of personal data before you sign in for the first time"},
"login.licence.full":function(d){return "In the full version, you can search through our "},
"login.licence.help":function(d){return "Help"},
"login.licence.agree":function(d){return "I accept the new terms and conditions"},
"login.licence.continue":function(d){return "Continue"},
"register.title":function(d){return "<strong>Register</strong> and you will receive all of the Seznam.cz services tailor-made to your needs."},
"register.continue":function(d){return "Continue"},
"register.agree":function(d){return "By registering you agree to the"},
"register.licence":function(d){return "terms of service"},
"register.licenceUrl":function(d){return "http://napoveda.seznam.cz/cz/licensing-agreement.html"},
"register.email":function(d){return "Any email address"},
"register.password":function(d){return "Password"},
"register.password2":function(d){return "Re-enter the password"},
"register.new":function(d){return "I don't have an email address and I want to create one "},
"register.login":function(d){return "I'm registered and I want to sign in"},
"register.resend":function(d){return "Send verification code again"},
"register.resend2":function(d){return "Did you not receive the code?"},
"register.checkMail":function(d){return "Please check the email box to which we sent your new verification code."},
"register.finalize":function(d){return "To complete, click on the link that we sent to you by email or copy the code provided."},
"register.submit":function(d){return "Finish"},
"register.error.agree":function(d){return "Please accept the terms of service to continue "},
"register.error.403":function(d){return "The code entered is invalid"},
"register.error.404":function(d){return "This email address is already registered with us"},
"register.error.406":function(d){return "The password to register is missing"},
"register.error.407":function(d){return "Registration attempt temporarily blocked"},
"register.error.420":function(d){return "Your password is too weak"},
"register.error.421":function(d){return "Your password is too weak"},
"register.error.422":function(d){return "Your password is too short. Please enter a longer one"},
"register.error.423":function(d){return "Your password is too long. Please enter a shorter one"},
"register.error.424":function(d){return "The password contains invalid characters"},
"register.error.425":function(d){return "There must not be a space at the beginning or end of the password"},
"register.error.426":function(d){return "The passwords do not match"},
"register.error.427":function(d){return "This mailbox does not yet exist. Click on 'Continue' to register it."},
"register.error.430":function(d){return "Email address too short"},
"register.error.431":function(d){return "The email address entered is invalid"},
"register.error.500":function(d){return "Internal system error"}}
})(this);

