#
# $Id: Makefile 5334 2008-12-16 13:16:21Z ondrej.zara $
#


jsdoc:
	fakeroot ./deb-szn-util-jsdoc.sh

jsdoc2:
	fakeroot ./deb-szn-util-jsdoc2.sh

closure-compiler:
	fakeroot ./deb-szn-util-closure-compiler.sh
